import { ParserErrorHandler } from "./ParserErrorHandler";
import { isMeetingDay } from "./types/CourseData";
import type { CourseRow, CourseStatus, Instructor, Meeting, MeetingDays } from "./types/CourseData";
import { finder } from '@medv/finder';

setTimeout(() => {
    main();
}, 1000);

async function main() {
    const pe = new ParserErrorHandler();

    await showAllCourses(); // Wait for the new page to load
    const pagePE = new ParserErrorHandler();
    const data = grabCourseDataTable(pagePE);
    pe.mergeErrorList(pagePE.getErrors());

    pe.flush();
}

/**
 * Expects to be called on the results page.
 * @returns an array of objects containing the extracted data
 */
function grabCourseDataTable(pe: ParserErrorHandler): CourseRow[] {
    let table = document.getElementById("table1");
    if (!table) {
        pe.newError({
            errorType: "MissingElement",
            message: "Unable to find the table1 element in the <body>. Skipping page",
            received: "null",
            expected: "element of ID table1",
            elementPath: finder(document.body),
            html: `Full document scanned (Size: ${document.body.getHTML.length})`,
            stackTrace: getStackTrace(), 
            page: getCurrentPage(),
        });
        return []
    }

    let tbodyGet = table.getElementsByTagName("tbody");
    let tbody = tbodyGet.item(0);
    if (!tbody) {
        pe.newError({
            errorType: "UnexpectedState",
            message: "<tbody> elements inside the #table1 element should always be > 0",
            received: "null",
            expected: "<tbody> element",
            elementPath: finder(table),
            html: table.getHTML(),
            stackTrace: getStackTrace(), 
            page: getCurrentPage(),
        })
        return []
    }

    tbody.querySelectorAll("tr").forEach(tr => {
        const rowPE = new ParserErrorHandler();
        parseTableRow(tr, rowPE);
        pe.mergeErrorList(rowPE.getErrors());
    });

    return [];
}

/**
 * Helper function to parse a row in the data table into a CourseRow object
 * @param tableRow to parse
 */
function parseTableRow(tableRow: HTMLTableRowElement, pe: ParserErrorHandler): CourseRow | null {
    /** Get a <td> element with the data-property attribute equal to pro: string */
    const getCell = (prop: string) => tableRow.querySelector<HTMLTableCellElement>(`td[data-property="${prop}"]`);

    // The data id is unique to every course element as assigned in banner and its how the scraper will identify them.
    // If we cannot find it, we should not continue to parse this row.
    const idStr: string | null = tableRow.getAttribute("data-id")
    if (idStr === null) {
        pe.newError({
            errorType: "MissingElement",
            received: "Undefined data-id attribute",
            expected: "An attribute of type data-id on element",
            elementPath: finder(tableRow),
            html: tableRow.getHTML(),
            stackTrace: getStackTrace(),
            page: getCurrentPage(),
        });
        return null;
    }
    
    // All the ids generated by banner should be a number. If not, lets skip this row
    const id: number = Number.parseInt(idStr);
    if (isNaN(id)) {
        pe.newError({
            errorType: "StringParse",
            received: `NaN value for data-id: ${idStr}`,
            expected: "A parseable number value for data-id attribute",
            elementPath: finder(tableRow),
            html: "",
            stackTrace: getStackTrace(),
            page: getCurrentPage(),
        });
        return null;
    }

    const courseTitle: string = getCell("courseTitle")?.querySelector("a")?.textContent.trim() ?? "";
    if (!courseTitle) {
        pe.newError({
            errorType: "MissingElement",
            received: `Undefined`,
            expected: "A cell with data-property tag of courseTitle with an <a> tag containing course title",
            elementPath: finder(tableRow),
            html: tableRow.getHTML(),
            stackTrace: getStackTrace(),
            page: getCurrentPage(),
        });
    }

    const subjectWithDesc: string | undefined = getCell("subjectDescription")?.textContent.trim();
    if (!subjectWithDesc) {
        pe.newError({
            errorType: "MissingElement",
            received: `Undefined`,
            expected: "A element with data-property attribute of subjectDescription",
            elementPath: finder(tableRow),
            html: tableRow.getHTML(),
            stackTrace: getStackTrace(),
            page: getCurrentPage(),
        });
    }

    const subjectID: string = subjectWithDesc?.substring(0, 3) ?? ""; // [0] is the three letter code
    if (!subjectID || subjectID.length != 3) {
        pe.newError({
            errorType: "StringParse",
            received: subjectWithDesc ?? "undefined",
            expected: "Value with pattern 'XXX-Expanded Course Subject Name'",
            elementPath: finder(tableRow),
            html: "",
            stackTrace: getStackTrace(),
            page: getCurrentPage(),
        });
    }
    const subjectDesc = subjectWithDesc?.substring(4) ?? ""; // The subject description

    const courseNumber: number = Number.parseInt(getCell("courseNumber")?.textContent.trim() ?? "");
    if (isNaN(courseNumber)) {
        pe.newError({
            errorType: "StringParse",
            received: `NaN value for tag text content: ${courseNumber}`,
            expected: "parseable number value",
            elementPath: finder(tableRow),
            html: "",
            stackTrace: getStackTrace(),
            page: getCurrentPage(),
        });
    }

    const sectionNumber: number = Number.parseInt(getCell("sequenceNumber")?.textContent.trim() ?? "");
    if (isNaN(sectionNumber)) {
        pe.newError({
            errorType: "StringParse",
            received: `NaN value for tag text content: ${sectionNumber}`,
            expected: "parseable number value",
            elementPath: finder(tableRow),
            html: "",
            stackTrace: getStackTrace(),
            page: getCurrentPage(),
        });
    }

    const creditHours: number = Number.parseInt(getCell("creditHours")?.textContent.trim() ?? "");
    if (isNaN(creditHours)) {
        pe.newError({
            errorType: "StringParse",
            received: `NaN value in tag text content: ${creditHours}`,
            expected: "parseable number value",
            elementPath: finder(tableRow),
            html: "",
            stackTrace: getStackTrace(),
            page: getCurrentPage(),
        });
    }

    const crn: number = Number.parseInt(getCell("courseReferenceNumber")?.textContent.trim() ?? "");
    if (isNaN(crn)) {
        pe.newError({
            errorType: "StringParse",
            received: `NaN value in text content of tag: ${crn}`,
            expected: "parseable number value",
            elementPath: finder(tableRow),
            html: "",
            stackTrace: getStackTrace(),
            page: getCurrentPage(),
        });
    }

    const term: string | undefined = getCell("term")?.textContent.trim() ?? "";
    if (!term) {
        pe.newError({
            errorType: "MissingElement",
            received: `Undefined`,
            expected: "A element with data-property attribute of term",
            elementPath: finder(tableRow),
            html: tableRow.getHTML(),
            stackTrace: getStackTrace(),
            page: getCurrentPage(),
        });
    }

    const instructorCell: HTMLTableCellElement | null = getCell("instructor");
    const instructors: Instructor[] = [];
    if (!instructorCell) {
        pe.newError({
            errorType: "MissingElement",
            received: `Undefined`,
            expected: "A element with data-property attribute of instructor",
            elementPath: finder(tableRow),
            html: tableRow.getHTML(),
            stackTrace: getStackTrace(),
            page: getCurrentPage(),
        });
    } else {
        instructorCell.childNodes.forEach(child => {
            const childText = child.textContent?.trim() ?? "";
            if (child instanceof HTMLAnchorElement) {
                const name = child.textContent.trim();

                let email = child.href.trim();
                if (email.startsWith("mailto:")) {
                    email = email.substring(7); // strip prefix
                }

                // check if next is a (Primary)
                let isPrimary = false;
                let next = child.nextSibling?.textContent?.trim() ?? "";
                if (next.toLowerCase() === "(primary)") {
                    isPrimary = true;
                }

                const instructor: Instructor = {
                    name: name,
                    email: email,
                    isPrimary: isPrimary
                }

                instructors.push(instructor);
            }
        });
    }

    const meetings: any[] = []; // TODO: fix this, should not be of any[] type
    const meetingCell = getCell("meetingTime");
    if (!meetingCell) {
        pe.newError({
            errorType: "MissingElement",
            received: `Undefined`,
            expected: "A element with data-property attribute of meetingTime",
            elementPath: finder(tableRow),
            html: tableRow.getHTML(),
            stackTrace: getStackTrace(),
            page: getCurrentPage(),
        });
    }

    if (meetingCell instanceof HTMLTableCellElement) {
        Array.from(meetingCell?.children).forEach((meeting) => {
            const isOnline = meeting.textContent?.includes("Building: Online") ?? false;
            let type, building, room, startDateUnparsed, endDateUnparsed, meetingTimes: string = "";
            let meetingDays: MeetingDays = [];

            if(meeting instanceof HTMLDivElement && meeting.classList.contains("meeting")) {
                const rawMeetingDays = meeting.querySelector(".ui-pillbox-summary.screen-reader")?.textContent.split(",") ?? [];
                const normalizedMtgDays = rawMeetingDays.map(elm => elm.toLowerCase());
                meetingDays = normalizedMtgDays.filter(isMeetingDay);

                // get the meeting days that we failed to parse that aren't none or empty
                const failedParsingDays = normalizedMtgDays.filter(elm => elm !== "none" && elm !== "" && !isMeetingDay(elm));

                if (failedParsingDays.length > 0) {
                    pe.newError({
                        errorType: "StringParse",
                        received: `${failedParsingDays}`,
                        expected: "Valid days of the week strings",
                        elementPath: finder(meeting),
                        html: meeting.getHTML(),
                        stackTrace: getStackTrace(),
                        page: getCurrentPage()
                    });
                }

                meetingTimes = meeting.querySelector(".ui-pillbox")?.nextSibling?.textContent?.trim() ?? ""; // Next to convert this into proper 24 HR times
                Array.from(meeting.children).forEach((span) => {
                    if ((!(span instanceof HTMLSpanElement)) || span.classList.contains("ui-pillbox")) { return; }

                    const splitContent = span.textContent.trim().split(":");
                    const spanType = splitContent[0]?.trim().toLowerCase() ?? "";
                    const spanContent = splitContent[1]?.trim().toLowerCase() ?? "";

                    if (spanContent === "") {
                        pe.newError({
                            errorType: "UnexpectedState",
                            received: `Empty string after splitting '${splitContent}' by :`,
                            expected: "Anything but empty string",
                            elementPath: finder(meeting),
                            html: meeting.getHTML(),
                            stackTrace: getStackTrace(),
                            page: getCurrentPage(),
                        });
                    }

                    if (spanType && spanType !== "") {
                        switch(spanType) {
                            case "type":
                                type = spanContent;
                                break;
                            case "building":
                                building = spanContent;
                                break;
                            case "room":
                                room = spanContent;
                                break;
                            case "start date":
                                startDateUnparsed = spanContent;
                                break;
                            case "end date":
                                endDateUnparsed = spanContent;
                                break;
                            default:
                                pe.newError({
                                    errorType: "UnexpectedState",
                                    received: `Type: ${spanType}`,
                                    expected: "One of the many types within the case statement",
                                    elementPath: finder(span),
                                    html: span.getHTML(),
                                    stackTrace: getStackTrace(),
                                    page: getCurrentPage(),
                                });
                                break;
                        }
                    } else {
                        pe.newError({
                            errorType: "UnexpectedState",
                            received: `Empty span type`,
                            expected: "Anything but empty string",
                            elementPath: finder(meeting),
                            html: meeting.getHTML(),
                            stackTrace: getStackTrace(),
                            page: getCurrentPage(),
                        });
                    }
                })
                
                let constructedMeeting = {
                    days: meetingDays,
                    startTime: meetingTimes,
                    endTime: meetingTimes,
                    type: type,
                    building: building,
                    room: room,
                    startDate: startDateUnparsed,
                    endDate: endDateUnparsed
                };
                meetings.push(constructedMeeting)
            }
        });
    }

    const campusCell = getCell("campus");
    const campus = campusCell?.textContent.trim() ?? "";

    if (!campusCell) {
        pe.newError({
            errorType: "MissingElement",
            received: "Undefined element",
            expected: "Valid element",
            elementPath: finder(tableRow),
            html: tableRow.getHTML(),
            stackTrace: getStackTrace(),
            page: getCurrentPage(),
        });
    }

    const statusCell = getCell("status");

    if (!statusCell) {
        pe.newError({
            errorType: "MissingElement",
            received: "Undefined element",
            expected: "Valid element",
            elementPath: finder(tableRow),
            html: tableRow.getHTML(),
            stackTrace: getStackTrace(),
            page: getCurrentPage(),
        });
    }

    const fullRegex = /full/;
    const isFull = statusCell?.textContent.toLowerCase().search(fullRegex) !== -1;

    const seatMatcher = /(\d*?) of (\d*?) seats remain\. ?(\d*?) of (\d*?) waitlist seats remain\./;
    const seatAvailability = statusCell?.textContent.match(seatMatcher);
    let [seatsRemain, seatsTotal, waitRemain, waitTotal] = [-1, -1, -1, -1];

    // One element is the full match, the other 4 should be the capture groups.
    if (!seatAvailability || seatAvailability.length != 5) {
        pe.newError({
            errorType: "StringParse",
            received: `Array of ${seatAvailability}`,
            expected: "Exactly 5 elements in the regex matcher return",
            elementPath: finder(statusCell ?? tableRow),
            html: statusCell?.getHTML() ?? "",
            stackTrace: getStackTrace(),
            page: getCurrentPage(),
        });
    } else {
        // The regex will only match numbers, so we are safe to parse without checking errors
        seatsRemain = Number.parseInt(seatAvailability[1] ?? "");
        seatsTotal = Number.parseInt(seatAvailability[2] ?? "");
        waitRemain = Number.parseInt(seatAvailability[3] ?? "");
        waitTotal = Number.parseInt(seatAvailability[4] ?? "");
    }

    const courseStatus: CourseStatus = {
        isFull: isFull,
        seatsRemaining: seatsRemain,
        totalSeats: seatsTotal,
        waitlistRemaining: waitRemain,
        waitlistTotal: waitTotal,
    }

    const scheduleTypeCell = getCell("scheduleType");
    const scheduleType = scheduleTypeCell?.textContent.trim() ?? "";

    if (!scheduleTypeCell) {
        pe.newError({
            errorType: "MissingElement",
            received: "Undefined",
            expected: "Valid HTML element",
            elementPath: finder(tableRow),
            html: tableRow.getHTML(),
            stackTrace: getStackTrace(),
            page: getCurrentPage(),
        })
    }

    const attributeCell = getCell("attribute");
    const attributes: string[] = [];
    attributeCell?.querySelectorAll("span").forEach((e) => {
        const processed = e.textContent.trim();
        if (processed !== "") {
            attributes.push(processed);
        }
    });

    const linkedSectionCell = getCell("linked");
    const linked: string[] = [];
    Array.from(linkedSectionCell?.children ?? []).forEach((e) => {
        const processed = e.textContent.trim();
        if (processed !== "") {
            linked.push(processed);
        }
    });

    let didEmitError: boolean = false;
    if (pe.getErrorAmount() > 0) {
        didEmitError = true;
    }

    const row: CourseRow = {
        id: id,
        errorTriggered: didEmitError,
        title: courseTitle,
        subject: subjectID,
        subjectDesc: subjectDesc,
        courseNumber: courseNumber,
        sectionNumber: sectionNumber,
        creditHours: creditHours,
        crn: crn,
        term: term,
        instructor: instructors,
        meetings: meetings,
        campus: campus,
        status: courseStatus,
        scheduleType: scheduleType,
        attributes: attributes,
        linked: linked,
    }

    return row;
}

/**
 * Helper method to await pause until the results page loads.
 * @returns a promise that is only accepted once the results element is made visible.
 */
async function waitForResultPage(): Promise<void> {
    return new Promise<void>((resolve) => {
        // Select the body element which exists on the search and result page as the DOM element to observe
        const body = document.querySelector(".body-content.ui-layout-center");
        if (body === null) {
            throw new Error("Failed to get the body element: .body-content.ui-layout-center");
        }

        let searchLoadObserver = new MutationObserver((changes: MutationRecord[], observer: MutationObserver) => {
            let element = document.querySelector<HTMLElement>(".results-title")
            if (element && element.offsetParent != null) {
                observer.disconnect();
                resolve();
            }
        });

        searchLoadObserver.observe(body, {childList: true, subtree: true});
    });
}

/**
 * Helper function to click the search button then wait for results page. Only returns once the results page has loaded.
 */
async function showAllCourses() {
    // Find the search button
    const searchBtn = document.getElementById("search-go");
    if (searchBtn) {
        searchBtn.click();
    } else {
        console.warn("Unable to find the id=\"search-go\" element. Are you on the search page?");
    }

    // Wait for the results page elements to load
    await waitForResultPage();
}

/**
 * Helper script to get the total number of pages. Should be called on the results page.
 * @returns the total number of pages else -1
 */
function getTotalPages(): number {
    const span = document.querySelector<HTMLElement>(".paging-text.total-pages");
    if (!span) {
        console.warn("Unable to find the total page number element. Are we on the results page?");
        return -1;
    }

    let totalPages = Number.parseInt(span.innerText);
    return totalPages;
}

/**
 * Helper method to find the pagination input field and extract the vaue of it. Should be called on the results page.
 * @returns the page number else -1
 */
function getCurrentPage(): number {
    const input = document.querySelector<HTMLInputElement>('.page-number.enabled');
    if (!input) {
        console.warn("Unable to find the pagination input field");
        return -1;
    }

    return Number.parseInt(input.value);
}

function getStackTrace(): string {
    const stackError = new Error("error made with the purpose to retreive the stack trace")
    return stackError.stack ?? "";
}