import { ParserErrorHandler } from "./ParserErrorHandler";
import { asDayNumber, asHourNumber, asMinuteNumber, asMonthNumber, isMeetingDay } from "./types/CourseData";
import type { CourseRow, CourseStatus, DayNumber, Instructor, Meeting, MeetingDays, MonthNumber, ParsedDate, Time24Hour } from "./types/CourseData";
import { finder } from '@medv/finder';

setTimeout(() => {
    main();
}, 1000);

async function main() {
    const pe = new ParserErrorHandler();

    await showAllCourses(); // Wait for the new page to load

    const totalPages = 1;
    for (let i = 1; i <= totalPages; i++) {
        let pagePE = new ParserErrorHandler();

        const paginator = document.querySelector<HTMLInputElement>(".page-number");
        if (!paginator) {
            throw new Error("Unable to find the paginator element.")
        }

        await setCurrentPage(paginator, i);
        const data = grabCourseDataTable(pagePE);
        pe.mergeErrorList(pagePE.getErrors());
        console.log(data);
    }
    
    pe.flush();
}

/**
 * Grabs the course data from the current page.
 * @returns an array of objects containing the extracted data
 */
function grabCourseDataTable(pe: ParserErrorHandler): CourseRow[] {
    const rowArray: CourseRow[] = [];
    let table = document.getElementById("table1");
    if (!table) {
        pe.newError({
            errorType: "MissingElement",
            message: "Unable to find the table1 element in the <body>. Skipping page",
            received: "null",
            expected: "element of ID table1",
            elementPath: finder(document.body),
            html: `Full document scanned (Size: ${document.body.getHTML.length})`,
            stackTrace: getStackTrace(), 
            page: getCurrentPage(),
        });
        return [];
    }

    let tbodyGet = table.getElementsByTagName("tbody");
    let tbody = tbodyGet.item(0);
    if (!tbody) {
        pe.newError({
            errorType: "UnexpectedState",
            message: "<tbody> elements inside the #table1 element should always be > 0",
            received: "null",
            expected: "<tbody> element",
            elementPath: finder(table),
            html: table.getHTML(),
            stackTrace: getStackTrace(), 
            page: getCurrentPage(),
        })
        return [];
    }

    tbody.querySelectorAll("tr").forEach(tr => {
        const rowPE = new ParserErrorHandler();
        const rowData = parseTableRow(tr, rowPE);
        if (rowData) {
            rowArray.push(rowData);
        }

        pe.mergeErrorList(rowPE.getErrors());
    });

    return rowArray;
}

/**
 * Helper function to parse a row in the data table into a CourseRow object
 * @param tableRow to parse
 */
function parseTableRow(tableRow: HTMLTableRowElement, pe: ParserErrorHandler): CourseRow | null {
    /** Get a <td> element with the data-property attribute equal to pro: string */
    const getCell = (prop: string) => tableRow.querySelector<HTMLTableCellElement>(`td[data-property="${prop}"]`);

    // The data id is unique to every course element as assigned in banner and its how the scraper will identify them.
    // If we cannot find it, we should not continue to parse this row.
    const idStr: string | null = tableRow.getAttribute("data-id")
    if (idStr === null) {
        pe.newError({
            errorType: "MissingElement",
            received: "Undefined data-id attribute",
            expected: "An attribute of type data-id on element",
            elementPath: finder(tableRow),
            html: tableRow.getHTML(),
            stackTrace: getStackTrace(),
            page: getCurrentPage(),
        });
        return null;
    }
    
    // All the ids generated by banner should be a number. If not, lets skip this row
    const id: number = Number.parseInt(idStr);
    if (isNaN(id)) {
        pe.newError({
            errorType: "StringParse",
            received: `NaN value for data-id: ${idStr}`,
            expected: "A parseable number value for data-id attribute",
            elementPath: finder(tableRow),
            html: "",
            stackTrace: getStackTrace(),
            page: getCurrentPage(),
        });
        return null;
    }

    const courseTitle: string = getCell("courseTitle")?.querySelector("a")?.textContent.trim() ?? "";
    if (!courseTitle) {
        pe.newError({
            errorType: "MissingElement",
            received: `Undefined`,
            expected: "A cell with data-property tag of courseTitle with an <a> tag containing course title",
            elementPath: finder(tableRow),
            html: tableRow.getHTML(),
            stackTrace: getStackTrace(),
            page: getCurrentPage(),
        });
    }

    const subjectWithDesc: string | undefined = getCell("subjectDescription")?.textContent.trim();
    if (!subjectWithDesc) {
        pe.newError({
            errorType: "MissingElement",
            received: `Undefined`,
            expected: "A element with data-property attribute of subjectDescription",
            elementPath: finder(tableRow),
            html: tableRow.getHTML(),
            stackTrace: getStackTrace(),
            page: getCurrentPage(),
        });
    }

    const subjectID: string = subjectWithDesc?.substring(0, 3) ?? ""; // [0] is the three letter code
    if (!subjectID || subjectID.length != 3) {
        pe.newError({
            errorType: "StringParse",
            received: subjectWithDesc ?? "undefined",
            expected: "Value with pattern 'XXX-Expanded Course Subject Name'",
            elementPath: finder(tableRow),
            html: "",
            stackTrace: getStackTrace(),
            page: getCurrentPage(),
        });
    }
    const subjectDesc = subjectWithDesc?.substring(4) ?? ""; // The subject description

    const courseNumber: number = Number.parseInt(getCell("courseNumber")?.textContent.trim() ?? "");
    if (isNaN(courseNumber)) {
        pe.newError({
            errorType: "StringParse",
            received: `NaN value for tag text content: ${courseNumber}`,
            expected: "parseable number value",
            elementPath: finder(tableRow),
            html: "",
            stackTrace: getStackTrace(),
            page: getCurrentPage(),
        });
    }

    const sectionNumber: number = Number.parseInt(getCell("sequenceNumber")?.textContent.trim() ?? "");
    if (isNaN(sectionNumber)) {
        pe.newError({
            errorType: "StringParse",
            received: `NaN value for tag text content: ${sectionNumber}`,
            expected: "parseable number value",
            elementPath: finder(tableRow),
            html: "",
            stackTrace: getStackTrace(),
            page: getCurrentPage(),
        });
    }

    const creditHours: number = Number.parseInt(getCell("creditHours")?.textContent.trim() ?? "");
    if (isNaN(creditHours)) {
        pe.newError({
            errorType: "StringParse",
            received: `NaN value in tag text content: ${creditHours}`,
            expected: "parseable number value",
            elementPath: finder(tableRow),
            html: "",
            stackTrace: getStackTrace(),
            page: getCurrentPage(),
        });
    }

    const crn: number = Number.parseInt(getCell("courseReferenceNumber")?.textContent.trim() ?? "");
    if (isNaN(crn)) {
        pe.newError({
            errorType: "StringParse",
            received: `NaN value in text content of tag: ${crn}`,
            expected: "parseable number value",
            elementPath: finder(tableRow),
            html: "",
            stackTrace: getStackTrace(),
            page: getCurrentPage(),
        });
    }

    const term: string | undefined = getCell("term")?.textContent.trim() ?? "";
    if (!term) {
        pe.newError({
            errorType: "MissingElement",
            received: `Undefined`,
            expected: "A element with data-property attribute of term",
            elementPath: finder(tableRow),
            html: tableRow.getHTML(),
            stackTrace: getStackTrace(),
            page: getCurrentPage(),
        });
    }

    const instructorCell: HTMLTableCellElement | null = getCell("instructor");
    const instructors: Instructor[] = [];
    if (!instructorCell) {
        pe.newError({
            errorType: "MissingElement",
            received: `Undefined`,
            expected: "A element with data-property attribute of instructor",
            elementPath: finder(tableRow),
            html: tableRow.getHTML(),
            stackTrace: getStackTrace(),
            page: getCurrentPage(),
        });
    } else {
        instructorCell.childNodes.forEach(child => {
            const childText = child.textContent?.trim() ?? "";
            if (child instanceof HTMLAnchorElement) {
                const name = child.textContent.trim();

                let email = child.href.trim();
                if (email.startsWith("mailto:")) {
                    email = email.substring(7); // strip prefix
                }

                // check if next is a (Primary)
                let isPrimary = false;
                let next = child.nextSibling?.textContent?.trim() ?? "";
                if (next.toLowerCase() === "(primary)") {
                    isPrimary = true;
                }

                const instructor: Instructor = {
                    name: name,
                    email: email,
                    isPrimary: isPrimary
                }

                instructors.push(instructor);
            }
        });
    }

    const meetings: Meeting[] = [];
    const meetingCell = getCell("meetingTime");
    if (!meetingCell) {
        pe.newError({
            errorType: "MissingElement",
            received: `Undefined`,
            expected: "A element with data-property attribute of meetingTime",
            elementPath: finder(tableRow),
            html: tableRow.getHTML(),
            stackTrace: getStackTrace(),
            page: getCurrentPage(),
        });
    }

    if (meetingCell instanceof HTMLTableCellElement) {
        Array.from(meetingCell?.children).forEach((meeting) => {
            const isOnline = meeting.textContent?.includes("Building: Online") ?? false;
            let [ type, building, room, startDateUnparsed, endDateUnparsed, meetingTimes ] = [ "", "", "", "", "", ""];
            let meetingDays: MeetingDays = [];

            if(meeting instanceof HTMLDivElement && meeting.classList.contains("meeting")) {
                const rawMeetingDays = meeting.querySelector(".ui-pillbox-summary.screen-reader")?.textContent.split(",") ?? [];
                const normalizedMtgDays = rawMeetingDays.map(elm => elm.toLowerCase());
                meetingDays = normalizedMtgDays.filter(isMeetingDay);

                // get the meeting days that we failed to parse that aren't none or empty
                const failedParsingDays = normalizedMtgDays.filter(elm => elm !== "none" && elm !== "" && !isMeetingDay(elm));

                if (failedParsingDays.length > 0) {
                    pe.newError({
                        errorType: "StringParse",
                        received: `${failedParsingDays}`,
                        expected: "Valid days of the week strings",
                        elementPath: finder(meeting),
                        html: meeting.getHTML(),
                        stackTrace: getStackTrace(),
                        page: getCurrentPage()
                    });
                }

                meetingTimes = meeting.querySelector(".ui-pillbox")?.nextSibling?.textContent?.trim() ?? ""; // Next to convert this into proper 24 HR times
                const meetingSplit = meetingTimes.split("-");
                const meetingStartUnparsed = meetingSplit[0]?.trim();
                const meetingEndUnparsed = meetingSplit[1]?.trim();

                if (!isOnline && (meetingSplit.length !== 2 || !meetingStartUnparsed || !meetingEndUnparsed)) {
                    pe.newError({
                        errorType: "StringParse",
                        received: `${meetingTimes}`,
                        expected: "Exactly two valid elements after splitting by -",
                        elementPath: finder(meeting),
                        html: meeting.getHTML(),
                        stackTrace: getStackTrace(),
                        page: getCurrentPage()
                    });
                }

                const pmMatcher = /pm/mi // if its matched, its PM else its AM

                const meetingStartIsPM: boolean = meetingStartUnparsed?.match(pmMatcher)?.length === 1 ? true : false;
                const startHourMinSplit = (meetingStartUnparsed?.substring(0, 5) ?? "").split(":");
                const startHourParsed12Hr = Number.parseInt(startHourMinSplit[0] ?? "");
                let startHourParsed = startHourParsed12Hr;
                if (meetingStartIsPM && startHourParsed12Hr != 12) {
                    startHourParsed += 12;   
                }
                const startMinParsed = Number.parseInt(startHourMinSplit[1] ?? "");

                const meetingEndIsPM: boolean = meetingEndUnparsed?.match(pmMatcher)?.length === 1 ? true : false;
                const endHourMinSplit = (meetingEndUnparsed?.substring(0, 5) ?? "").split(":");
                const endHourParsed12Hr = Number.parseInt(endHourMinSplit[0] ?? "");
                let endHourParsed = endHourParsed12Hr;
                if (meetingEndIsPM && endHourParsed12Hr != 12) {
                    endHourParsed += 12;   
                }
                const endMinParsed = Number.parseInt(endHourMinSplit[1] ?? "");

                let startTime24Hour: Time24Hour = { hour: asHourNumber(0), minute: asMinuteNumber(0) };
                let endTime24Hour: Time24Hour = { hour: asHourNumber(0), minute: asMinuteNumber(0) };

                if (!isOnline) {
                    try {
                        startTime24Hour = {
                            hour: asHourNumber(startHourParsed),
                            minute: asMinuteNumber(startMinParsed),
                        }
                        endTime24Hour = {
                            hour: asHourNumber(endHourParsed),
                            minute: asMinuteNumber(endMinParsed),
                        }
                    } catch {
                        pe.newError({
                            errorType: "StringParse",
                            received: `${meetingTimes}`,
                            expected: "A parsed result consistent with hour (0-24) and minute (0-60) ranges",
                            elementPath: finder(meeting),
                            html: meeting.getHTML(),
                            stackTrace: getStackTrace(),
                            page: getCurrentPage()
                        });
                    }
                }    

                Array.from(meeting.children).forEach((span) => {
                    if ((!(span instanceof HTMLSpanElement)) || span.classList.contains("ui-pillbox")) { return; }

                    const splitContent = span.textContent.trim().split(":");
                    const spanType = splitContent[0]?.trim().toLowerCase() ?? "";
                    const spanContent = splitContent[1]?.trim().toLowerCase() ?? "";

                    if (spanContent === "") {
                        pe.newError({
                            errorType: "UnexpectedState",
                            received: `Empty string after splitting '${splitContent}' by :`,
                            expected: "Anything but empty string",
                            elementPath: finder(meeting),
                            html: meeting.getHTML(),
                            stackTrace: getStackTrace(),
                            page: getCurrentPage(),
                        });
                    }

                    if (spanType && spanType !== "") {
                        switch(spanType) {
                            case "type":
                                type = spanContent;
                                break;
                            case "building":
                                building = spanContent;
                                break;
                            case "room":
                                room = spanContent;
                                break;
                            case "start date":
                                startDateUnparsed = spanContent;
                                break;
                            case "end date":
                                endDateUnparsed = spanContent;
                                break;
                            default:
                                pe.newError({
                                    errorType: "UnexpectedState",
                                    received: `Type: ${spanType}`,
                                    expected: "One of the many types within the case statement",
                                    elementPath: finder(span),
                                    html: span.getHTML(),
                                    stackTrace: getStackTrace(),
                                    page: getCurrentPage(),
                                });
                                break;
                        }
                    } else {
                        pe.newError({
                            errorType: "UnexpectedState",
                            received: `Empty span type`,
                            expected: "Anything but empty string",
                            elementPath: finder(meeting),
                            html: meeting.getHTML(),
                            stackTrace: getStackTrace(),
                            page: getCurrentPage(),
                        });
                    }
                })
                
                let startDateParsed: ParsedDate = {
                    year: -1,
                    month: asMonthNumber(1),
                    day: asDayNumber(1)
                };

                let endDateParsed: ParsedDate = {
                    year: -1,
                    month: asMonthNumber(1),
                    day: asDayNumber(1)
                };

                try {
                    startDateParsed = parseDateString(startDateUnparsed);
                    endDateParsed = parseDateString(endDateUnparsed);
                } catch(e: unknown) {
                    let msg: string = "";

                    if (typeof e === "string") {
                        msg = e;
                    } else if (e instanceof Error) {
                        msg = e.message;
                    }

                    pe.newError({
                        errorType: "StringParse",
                        message: msg,
                        received: `${startDateUnparsed} and ${endDateUnparsed}`,
                        expected: "A valid MM/DD/YYYY string",
                        elementPath: finder(meeting),
                        html: meeting.getHTML(),
                        stackTrace: getStackTrace(),
                        page: getCurrentPage(),
                    });
                }

                let constructedMeeting: Meeting = {
                    days: meetingDays,
                    startTime: startTime24Hour,
                    endTime: endTime24Hour,
                    type: type,
                    building: building,
                    room: room,
                    isOnline: isOnline,
                    startDate: startDateParsed,
                    endDate: endDateParsed
                };
                meetings.push(constructedMeeting)
            }
        });
    }

    const campusCell = getCell("campus");
    const campus = campusCell?.textContent.trim() ?? "";

    if (!campusCell) {
        pe.newError({
            errorType: "MissingElement",
            received: "Undefined element",
            expected: "Valid element",
            elementPath: finder(tableRow),
            html: tableRow.getHTML(),
            stackTrace: getStackTrace(),
            page: getCurrentPage(),
        });
    }

    const statusCell = getCell("status");

    if (!statusCell) {
        pe.newError({
            errorType: "MissingElement",
            received: "Undefined element",
            expected: "Valid element",
            elementPath: finder(tableRow),
            html: tableRow.getHTML(),
            stackTrace: getStackTrace(),
            page: getCurrentPage(),
        });
    }

    const fullRegex = /full/;
    const isFull = statusCell?.textContent.toLowerCase().search(fullRegex) !== -1;

    const seatMatcher = /(\d*?) of (\d*?) seats remain\. ?(\d*?) of (\d*?) waitlist seats remain\./;
    const seatAvailability = statusCell?.textContent.match(seatMatcher);
    let [seatsRemain, seatsTotal, waitRemain, waitTotal] = [-1, -1, -1, -1];

    // One element is the full match, the other 4 should be the capture groups.
    if (!seatAvailability || seatAvailability.length != 5) {
        pe.newError({
            errorType: "StringParse",
            received: `Array of ${seatAvailability}`,
            expected: "Exactly 5 elements in the regex matcher return",
            elementPath: finder(statusCell ?? tableRow),
            html: statusCell?.getHTML() ?? "",
            stackTrace: getStackTrace(),
            page: getCurrentPage(),
        });
    } else {
        // The regex will only match numbers, so we are safe to parse without checking errors
        seatsRemain = Number.parseInt(seatAvailability[1] ?? "");
        seatsTotal = Number.parseInt(seatAvailability[2] ?? "");
        waitRemain = Number.parseInt(seatAvailability[3] ?? "");
        waitTotal = Number.parseInt(seatAvailability[4] ?? "");
    }

    const courseStatus: CourseStatus = {
        isFull: isFull,
        seatsRemaining: seatsRemain,
        totalSeats: seatsTotal,
        waitlistRemaining: waitRemain,
        waitlistTotal: waitTotal,
    }

    const scheduleTypeCell = getCell("scheduleType");
    const scheduleType = scheduleTypeCell?.textContent.trim() ?? "";

    if (!scheduleTypeCell) {
        pe.newError({
            errorType: "MissingElement",
            received: "Undefined",
            expected: "Valid HTML element",
            elementPath: finder(tableRow),
            html: tableRow.getHTML(),
            stackTrace: getStackTrace(),
            page: getCurrentPage(),
        })
    }

    const attributeCell = getCell("attribute");
    const attributes: string[] = [];
    attributeCell?.querySelectorAll("span").forEach((e) => {
        const processed = e.textContent.trim();
        if (processed !== "") {
            attributes.push(processed);
        }
    });

    const linkedSectionCell = getCell("linked");
    const linked: string[] = [];
    Array.from(linkedSectionCell?.children ?? []).forEach((e) => {
        const processed = e.textContent.trim();
        if (processed !== "") {
            linked.push(processed);
        }
    });

    let didEmitError: boolean = false;
    if (pe.getErrorAmount() > 0) {
        didEmitError = true;
    }

    const row: CourseRow = {
        id: id,
        errorTriggered: didEmitError,
        title: courseTitle,
        subject: subjectID,
        subjectDesc: subjectDesc,
        courseNumber: courseNumber,
        sectionNumber: sectionNumber,
        creditHours: creditHours,
        crn: crn,
        term: term,
        instructor: instructors,
        meetings: meetings,
        campus: campus,
        status: courseStatus,
        scheduleType: scheduleType,
        attributes: attributes,
        linked: linked,
    }

    return row;
}

/**
 * Parses the raw string of format MM/DD/YYYY (MDY) into a ParsedDate object.
 * If anything goes wrong, throws errors. Capture it in ParseError.
 * @param unparsed the string to parse
 * @returns ParsedDate object
 */
function parseDateString(unparsed: string): ParsedDate {
    let split: string[] = unparsed.split("/");
    if (split.length != 3) {
        throw new Error(`Splitting the unparsed date string (${unparsed}) by / did not yield exactly 3 elements.`);
    }

    // if the month and day are NaN (don't parse properly) then their type guards will throw errors
    const month: MonthNumber = asMonthNumber(Number.parseInt(split[0] ?? ""));
    const day: DayNumber = asDayNumber(Number.parseInt(split[1] ?? ""));
    const year: number = Number.parseInt(split[2] ?? "");

    if (Number.isNaN(year)) {
        throw new Error(`The parsed year was NaN: ${unparsed}`);
    }

    const parsed: ParsedDate = {
        year: year,
        month: month,
        day: day,
    }

    return parsed;
}

/**
 * Helper method to await pause until the results page loads.
 * @returns a promise that is only accepted once the results element is made visible.
 */
async function waitForResultPage(): Promise<void> {
    return new Promise<void>((resolve) => {
        // Select the body element which exists on the search and result page as the DOM element to observe
        const body = document.querySelector(".body-content.ui-layout-center");
        if (body === null) {
            throw new Error("Failed to get the body element: .body-content.ui-layout-center");
        }

        let searchLoadObserver = new MutationObserver((changes: MutationRecord[], observer: MutationObserver) => {
            let element = document.querySelector<HTMLElement>(".results-title")
            if (element && element.offsetParent != null) {
                observer.disconnect();
                resolve();
            }
        });

        searchLoadObserver.observe(body, {childList: true, subtree: true});
    });
}

/**
 * Helper function to click the search button then wait for results page. Only returns once the results page has loaded.
 */
async function showAllCourses() {
    // Find the search button
    const searchBtn = document.getElementById("search-go");
    if (searchBtn) {
        searchBtn.click();
    } else {
        console.warn("Unable to find the id=\"search-go\" element. Are you on the search page?");
    }

    // Wait for the results page elements to load
    await waitForResultPage();
}

/**
 * Helper script to get the total number of pages. Should be called on the results page.
 * @returns the total number of pages else -1
 */
function getTotalPages(): number {
    const span = document.querySelector<HTMLElement>(".paging-text.total-pages");
    if (!span) {
        console.warn("Unable to find the total page number element. Are we on the results page?");
        return -1;
    }

    let totalPages = Number.parseInt(span.innerText);
    return totalPages;
}

/**
 * Helper method to find the pagination input field and extract the vaue of it. Should be called on the results page.
 * @returns the page number else -1
 */
function getCurrentPage(): number {
    const input = document.querySelector<HTMLInputElement>('.page-number.enabled');
    if (!input) {
        console.warn("Unable to find the pagination input field");
        return -1;
    }

    return Number.parseInt(input.value);
}

/**
 * Sets the current page to the one requested
 * @param input the paginator input element
 * @param pgNum page to navigate to
 */
async function setCurrentPage(input: HTMLInputElement, pgNum: number): Promise<void> {
    // TODO: handle when the page number is out of bounds, it throws no errors, but woudl silent fail
    return new Promise((resolve) => {

        // Native getter and setter for the 'value' element. 
        // jQuery and other libraries might redefine this
        // so it's good we get the native function for it
        const descriptor = Object.getOwnPropertyDescriptor(
            HTMLInputElement.prototype,
            'value'
        );
    
        if (!descriptor || !descriptor.set) {
            return Promise.reject(new Error('unable to get native value setter for paginator'))
        }
    
        descriptor.set.call(input, pgNum);
    
        input.dispatchEvent(new Event('change', { bubbles: true }));
    
        // When the spinner's display property gets set to "none" the page has finished loading
        const targetNode = document.getElementById("spinner");
        if (!targetNode) {
            return Promise.reject(new Error("unable to get the element with id spinner"))
        }
    
        const callback = (mutationList: MutationRecord[], observer: MutationObserver) => {
            for (const mutation of mutationList) {
                if (mutation.type === "attributes" && window.getComputedStyle(targetNode).display === "none") {
                    observer.disconnect();
                    resolve();
                }
            }
        };
    
        const observer = new MutationObserver(callback);
        observer.observe(targetNode, { attributes: true, childList: true, subtree: true });
    })
}

function getStackTrace(): string {
    const stackError = new Error("error made with the purpose to retreive the stack trace")
    return stackError.stack ?? "";
}